server:
  port: 8005
spring:
  profiles: user-hystrix-service0
  application:
    name: user-hystrix-service
## 数据库 配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot_example?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  # jpa配置
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
# eureka
eureka:
  instance:
    hostname: 127.0.0.1
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8003/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
ribbon:
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 2
  OkToRetryOnAperations: false
---
server:
  port: 8400
spring:
  profiles: user-hystrix-service1
  application:
    name: user-hystrix-service
  ## 数据库 配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot_example?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  # jpa配置
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
# eureka
eureka:
  instance:
    hostname: 127.0.0.1
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/,http://localhost:8101/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
ribbon:
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 2
  OkToRetryOnAperations: false
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
server:
  port: 8401
spring:
  profiles: user-hystrix-service2
  application:
    name: user-hystrix-service
  ## 数据库 配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot_example?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  # jpa配置
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
# eureka
eureka:
  instance:
    hostname: 127.0.0.1
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/,http://localhost:8101/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
ribbon:
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 2
  OkToRetryOnAperations: false
