server:
  port: 8003
spring:
  application:
    name: eureka-server
  profiles: eureka-server0
# eureka 配置
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true  # 通过ip注册
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
---
spring:
  profiles: eureka-server1
  application:
    name: eureka-server
server:
  port: 8100
# eureka 配置
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true  # 通过ip注册
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8100/eureka/,http://127.0.0.1:8101/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
---
spring:
  profiles: eureka-server2
  application:
    name: eureka-server
server:
  port: 8101
# eureka 配置
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true  # 通过ip注册
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8100/eureka/,http://127.0.0.1:8101/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000


